# Generated by Django 5.2.5 on 2025-08-08 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('n_animais', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinco', models.IntegerField()),
                ('animal_id_c', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('femea', 'Femea')], max_length=50)),
                ('meses', models.IntegerField()),
                ('categoria', models.CharField(choices=[('cordeiro(a)', 'Cordeiro'), ('borrego(a)', 'Borrego'), ('ovelha', 'Ovelha'), ('carneiro', 'Carneiro'), ('capão', 'Capao')], max_length=50)),
                ('peso_vivo_atual_kg', models.FloatField()),
                ('frequencia_livre', models.BooleanField(default=False)),
                ('frequencia', models.IntegerField(blank=True, null=True)),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='comedouro.lote')),
                ('raca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='comedouro.raca')),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('duracao', models.DurationField()),
                ('comportamento', models.TextField(blank=True, max_length=2500, null=True)),
                ('consumo_kg', models.FloatField()),
                ('peso_vivo_entrada_kg', models.FloatField()),
                ('peso_vivo_final_kg', models.FloatField()),
                ('gdm_entrada', models.FloatField()),
                ('gdm_final', models.FloatField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeições', to='comedouro.animal')),
            ],
        ),
    ]
