# Generated by Django 5.2.5 on 2025-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicao',
            name='duracao',
        ),
        migrations.AddField(
            model_name='refeicao',
            name='duracao_min',
            field=models.FloatField(default=0),
        ),
    ]
