# Generated by Django 5.2.5 on 2025-08-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0002_remove_refeicao_duracao_refeicao_duracao_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='duracao_min',
            field=models.FloatField(),
        ),
    ]
