# Generated by Django 5.2.5 on 2025-09-02 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0003_alter_refeicao_duracao_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brinco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='refeicao',
            old_name='horario',
            new_name='horario_entrada',
        ),
        migrations.RemoveField(
            model_name='refeicao',
            name='duracao_min',
        ),
        migrations.RemoveField(
            model_name='refeicao',
            name='gdm_entrada',
        ),
        migrations.RemoveField(
            model_name='refeicao',
            name='gdm_final',
        ),
        migrations.RemoveField(
            model_name='refeicao',
            name='peso_vivo_final_kg',
        ),
        migrations.AddField(
            model_name='refeicao',
            name='horario_saida',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='brinco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='comedouro.brinco'),
        ),
    ]
