# Generated by Django 5.2.5 on 2025-09-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0004_brinco_rename_horario_refeicao_horario_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso_vivo_atual_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
