# Generated by Django 5.2.5 on 2025-09-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0005_alter_animal_peso_vivo_atual_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='meses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
