# Generated by Django 5.2.5 on 2025-09-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0006_alter_animal_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='brinco',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Brinco',
        ),
    ]
