# Generated by Django 5.2.5 on 2025-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0007_alter_animal_brinco_delete_brinco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Raca',
        ),
    ]
