# Generated by Django 5.2.5 on 2025-09-02 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0008_alter_animal_raca_delete_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='refeicao',
            name='horario_saida',
            field=models.TimeField(),
        ),
    ]
