# Generated by Django 5.2.5 on 2025-09-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0009_alter_refeicao_data_alter_refeicao_horario_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='peso_vivo_atual_kg',
        ),
    ]
