# Generated by Django 5.2.5 on 2025-09-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0010_remove_animal_peso_vivo_atual_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(blank=True, null=True),
        ),
    ]
