# Generated by Django 5.2.5 on 2025-09-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0011_alter_animal_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brinco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=128)),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_id_c',
        ),
        migrations.AlterField(
            model_name='animal',
            name='brinco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='comedouro.brinco'),
        ),
    ]
