# Generated by Django 5.2.5 on 2025-09-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0012_brinco_remove_animal_animal_id_c_alter_animal_brinco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinco',
            name='numero',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brinco',
            name='tag_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
