# Generated by Django 5.2.5 on 2025-09-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0013_alter_brinco_numero_alter_brinco_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('femea', 'Femea')], max_length=50, null=True),
        ),
    ]
