# Generated by Django 5.2.5 on 2025-10-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedouro', '0014_alter_animal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinco',
            name='numero',
            field=models.CharField(max_length=128),
        ),
    ]
