# Generated by Django 5.2.3 on 2025-06-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_animais', models.IntegerField(default=0)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_brinco', models.IntegerField()),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('idade_dias', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('consumo_diario', models.FloatField(blank=True, null=True)),
                ('custo_diario_racao', models.FloatField(blank=True, null=True)),
                ('alimentacao_frequencia_livre', models.BooleanField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animais.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('peso_na_entrada', models.FloatField(blank=True, null=True)),
                ('duracao_refeicao', models.DurationField(blank=True, null=True)),
                ('peso_racao', models.FloatField(blank=True, null=True)),
                ('variacao_peso', models.FloatField(blank=True, null=True)),
                ('comportamento', models.TextField(blank=True, default='')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animais.animal')),
            ],
        ),
    ]
